### ISSUE TITLE
fix: typo

### ISSUE THREAD

**Issue by tusharnankani** [HarshKapadia2/css-linking-types#1]
https://github.com/HarshKapadia2/css-linking-types/blob/291c5ba1a684fd6b5767edc9391f7b5b8346e293/assig-4.html#L45

**Comment by HarshKapadia2** [comment]
Thank you, @tusharnankani!

**Comment by HarshKapadia2** [comment]
Oops!
I thought that this issue referred to the `index.html` file. Anyways, I found the typo in that file as well.

**Comment by HarshKapadia2** [comment]
The typo in `assig-4.html` was corrected in commit 6b4c8d20a7b0e546a9603a0605882ef96a3b95b9.
